### ISSUE TITLE
Add project: jupyterlab-executor

### ISSUE THREAD

**Issue by gavincyi** [ml-tooling/best-of-jupyter#24]
**Project details:**

- Project Name: jupyterlab-executor
- Github URL: https://github.com/gavincyi/jupyterlab-executor
- Category:   JupyterLab Extensions
- License: BSD-3
- Package Managers:  pypi and npm

**Additional context:**

**Comment by lukasmasuch** [comment]
Thanks for the contribution. I just merged the PR: https://github.com/ml-tooling/best-of-jupyter/pull/23
